### ISSUE TITLE
Create the default dict formatting

### ISSUE THREAD

**Issue by vmesel** [vmesel/FastaDB#2]
Create the file structure for the .FDB file.

It must contain:
- ID
- Description
- Sequence
- Filename
- Date
- User
- Observations

**Comment by vmesel** [comment]
Default formating needs to be changed! We need to make all gene dicts as gene, and the ID of the Gene should be his identifier

**Comment by inaciomdrs** [comment]
@vmesel I confess that didn't understand this part "make all gene dicts as gene". Could you explain more about it?
